server:
  port: 8401
  
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务注册中心
    sentinel:
      transport:
        dashboard: localhost:8080   # 配置sentinel dashboard地址
        port: 8719 # 默认8719端口，加入被占用，会自动从8719开始依次+1扫描，直至找到未被占用端口

      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
        
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

# nacos中sentinel流控配置如下格式
# [
#     {
#         "resource": "/rateLimit/byUrl", 资源名称
#         "limitApp": "default",          来源应用，默认default 
#         "grade": 1,                     阈值类型，0表示线程数，1表示QPS
#         "count": 1,                     单机阈值
#         "strategy": 0,                  流控模式，0表示直接，1表示关联，2表示链路
#         "controlBehavior": 0,           流控效果，0表示快速失败，1表示warm up，2表示排队等待
#         "clusterMode": false            是否集群
#     }
# ]    