server:
  port: 80
    
eureka:
  client: 
    register-with-eureka: false #表示是否向注册中心注册自己，默认为true
#    fetch-registry: true #是否从注册中心抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
           #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      
#设置feign客户端的超时时间(openfeign默认支持ribbon)
ribbon:
  #指的是建立连接所用时间，适用于网络状态正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用子u按所用的时间
  connectTimeout: 5000
  
logging:
  level:
  #feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug